CREATE TABLE PLAYER (
  ID         BIGINT AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50),
  LAST_NAME  VARCHAR(50),
  DEPTH      INTEGER,
  POSITION   VARCHAR(20),
  JERSEY     INTEGER,
  TEAM       CHAR(3),
);

CREATE TABLE PLAYER_RANKING (
  ID         BIGINT AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50),
  LAST_NAME  VARCHAR(50),
  RANKING    INTEGER,
  JERSEY     INTEGER,
  TEAM       CHAR(3),
  HASH_KEY   VARCHAR(50)
);